# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  ACCESS_KEY_ID: $(accessKeyId)
  AWS_BUCKET_NAME: $(awsBucketName)
  MAILER_AUTH_PASS: $(mailerAuthPass)
  MAILER_AUTH_USER: $(mailerAuthUser)
  MAILER_HOST: $(mailerHost)
  MAILER_PORT: $(mailerPort)
  MONGO_URI: $(mongoURI)
  MY_NAME: $(myName)
  MY_PHONE: $(myPhone)
  MY_POSITION: $(myPosition)
  REGION: $(region)
  SECRET: $(secret)
  SECRET_ACCESS_KEY: $(secretAccessKey)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.1'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    NODE_ENV=production npm start
  displayName: 'npm start'
