trigger:
- master

variables:
- group: my-variable-group
- name: ACCESS_KEY_ID
  value: $[variables.accessKeyId]
- name: AWS_BUCKET_NAME
  value: $[variables.awsBucketName]
- name: MAILER_AUTH_PASS
  value: $[variables.mailerAuthPass]
- name: MAILER_AUTH_USER
  value: $[variables.mailerAuthUser]
- name: MAILER_HOST
  value: $[variables.mailerHost]
- name: MAILER_PORT
  value: $[variables.mailerPort]
- name: MONGO_URI
  value: $[variables.mongoURI]
- name: MY_NAME
  value: $[variables.myName]
- name: MY_PHONE
  value: $[variables.myPhone]
- name: MY_POSITION
  value: $[variables.myPosition]
- name: REGION
  value: $[variables.region]
- name: SECRET
  value: $[variables.secret]
- name: SECRET_ACCESS_KEY
  value: $[variables.secretAccessKey]

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.1'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    NODE_ENV=production npm start
  displayName: 'npm start'
