# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  group: my-variable-group

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.1'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    echo $(mongoURI)
  env:
    NODE_ENV: 'production'
    MONGO_URI: $(mongoURI)
    SECRET: $(secret)
    ACCESS_KEY_ID: $(accessKeyId)
    SECRET_ACCESS_KEY: $(secretAccessKey)
    REGION: $(region)
    AWS_BUCKET_NAME: $(awsBucketName)
    MAILER_HOST: $(mailerHost)
    MAILER_PORT: $(mailerPort)
    MAILER_AUTH_USER: $(mailerAuthUser)
    MAILER_AUTH_PASS: $(mailerAuthPass)
    MY_NAME: $(myName)
    MY_POSITION: $(myPosition)
    MY_PHONE: $(myPhone)
  displayName: 'test variables'
